// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDORJiwwIcPsGA-0RWEM4Y_HZOFNqGtOW8',
    appId: '1:1010391577811:web:90303b12afb0351403d026',
    messagingSenderId: '1010391577811',
    projectId: 'flutter-chat-app-ce89b',
    authDomain: 'flutter-chat-app-ce89b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ce89b.firebasestorage.app',
    measurementId: 'G-H2YST50P56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrU1cz40BaqKxC9Vbvx7w7QgXnNLr9b3A',
    appId: '1:1010391577811:android:c9d852dadad0002403d026',
    messagingSenderId: '1010391577811',
    projectId: 'flutter-chat-app-ce89b',
    storageBucket: 'flutter-chat-app-ce89b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTAfSIWdDi-p0_3URyEOxt0d4vJk2uIoU',
    appId: '1:1010391577811:ios:6f797a9e0d6a6ce003d026',
    messagingSenderId: '1010391577811',
    projectId: 'flutter-chat-app-ce89b',
    storageBucket: 'flutter-chat-app-ce89b.firebasestorage.app',
    androidClientId: '1010391577811-tm0h10pragccvoi9v444o7irmf3do5f6.apps.googleusercontent.com',
    iosClientId: '1010391577811-ivdiabsj53fkrh9c8ibnh5mtd087fm3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTAfSIWdDi-p0_3URyEOxt0d4vJk2uIoU',
    appId: '1:1010391577811:ios:6f797a9e0d6a6ce003d026',
    messagingSenderId: '1010391577811',
    projectId: 'flutter-chat-app-ce89b',
    storageBucket: 'flutter-chat-app-ce89b.firebasestorage.app',
    androidClientId: '1010391577811-tm0h10pragccvoi9v444o7irmf3do5f6.apps.googleusercontent.com',
    iosClientId: '1010391577811-ivdiabsj53fkrh9c8ibnh5mtd087fm3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDORJiwwIcPsGA-0RWEM4Y_HZOFNqGtOW8',
    appId: '1:1010391577811:web:3d4d7bda407ee9fb03d026',
    messagingSenderId: '1010391577811',
    projectId: 'flutter-chat-app-ce89b',
    authDomain: 'flutter-chat-app-ce89b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ce89b.firebasestorage.app',
    measurementId: 'G-WZPTS4YDCE',
  );

}